name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Code Checkout 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install sqlalchemy pandas numpy pysqlite3 matplotlib
    
    - name: Install kaggle CLI
      run: |
        pip install kaggle
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Set up Kaggle API credentials
      run: |
        mkdir -p $HOME/.kaggle
        echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_API_KEY\"}" > $HOME/.kaggle/kaggle.json
        chmod 600 $HOME/.kaggle/kaggle.json
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_API_KEY: ${{ secrets.KAGGLE_API_KEY }}

    - name: Run tests
      run: |
        chmod +x project/test.sh
        ./project/test.sh